name: Test app
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "file:./test.db"
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Clear pnpm store
        run: pnpm store prune

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          echo "Removing existing Prisma packages..."
          rm -rf node_modules/@prisma node_modules/.prisma
          pnpm install --no-frozen-lockfile
          echo "Installed versions:"
          pnpm list prisma @prisma/client
          echo "Node modules content:"
          ls -la node_modules/.prisma || echo "No .prisma directory"
          ls -la node_modules/@prisma || echo "No @prisma directory"

      - name: Setup Prisma
        run: |
          echo "Setting up Prisma..."
          echo "Current working directory: $(pwd)"
          echo "Installing specific Prisma version..."
          pnpm remove prisma @prisma/client
          pnpm install -D prisma@5.10.2
          pnpm install @prisma/client@5.10.2
          echo "Installed Prisma versions:"
          pnpm list prisma @prisma/client
          echo "Generating Prisma client..."
          pnpm dlx prisma@5.10.2 generate
          echo "Checking generated client:"
          ls -la node_modules/.prisma || echo "No .prisma directory"
          ls -la node_modules/@prisma/client || echo "No client directory"

      - name: Build
        run: |
          echo "Starting build..."
          echo "TypeScript version:"
          pnpm tsc --version
          echo "tsconfig.json content:"
          cat tsconfig.json
          pnpm build

      - name: Run tests
        run: pnpm vitest run
