name: Test app
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "file:./test.db"
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Clear pnpm store
        run: pnpm store prune

      - name: Setup pnpm config
        run: |
          pnpm config set enable-pre-post-scripts true
          pnpm config set auto-install-peers true

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          rm -rf node_modules
          rm -rf pnpm-lock.yaml
          pnpm install
          pnpm approve-builds prisma @prisma/client

      - name: Setup Prisma
        run: |
          echo "Setting up Prisma..."
          echo "Current working directory: $(pwd)"
          pnpm install prisma
          pnpm install @prisma/client
          echo "Installed Prisma versions:"
          pnpm list prisma @prisma/client
          echo "Generating Prisma client..."
          rm -rf node_modules/.prisma/client
          pnpm prisma generate
          echo "Checking generated client:"
          ls -la node_modules/.prisma || echo "No .prisma directory"
          ls -la node_modules/@prisma/client || echo "No client directory"

      - name: Build
        run: |
          echo "Starting build..."
          echo "TypeScript version:"
          pnpm tsc --version
          echo "tsconfig.json content:"
          cat tsconfig.json
          pnpm build

      - name: Run tests
        run: pnpm vitest run
